import * as React from "react";
import _ from "src/i18n/locale";
import { Footer } from "src/atomic/organism/footer";
import NavigationBar from "src/atomic/organism/navbar";
import PageHeader from "../molecule/page-header";
export default function Electrolyte() {
    return React.createElement(React.Fragment, null,
        React.createElement(NavigationBar, null),
        React.createElement("div", { className: "ms-base-page pb-5" },
            React.createElement(PageHeader, { title: "ELECTROLYTE.HEAD", subtitleLevel2: "ELECTROLYTE.ABOUT", appId: 1507719251, appDownloadTitle: "ELECTROLYTE.DWN", imgSrc: "/img/page/electrolyte/electrolyte.svg", imgAlt: "ELECTROLYTE.IMG", imgH: 460, imgW: 440 }),
            React.createElement("section", null,
                React.createElement("h4", null, _("ELECTROLYTE.HEAD1")),
                React.createElement("p", { className: "mt-3" },
                    _("ELECTROLYTE.DESC1"),
                    React.createElement("a", { href: "https://ods.od.nih.gov/factsheets/Magnesium-HealthProfessional", target: "_blank" },
                        React.createElement("small", null,
                            React.createElement("i", null,
                                _("BTN.SRC1"),
                                "."))))),
            React.createElement("section", null,
                React.createElement("h4", null, _("ELECTROLYTE.HEAD2")),
                React.createElement("p", { className: "mt-3" },
                    _("ELECTROLYTE.DESC2"),
                    React.createElement("a", { href: "https://ods.od.nih.gov/factsheets/Calcium-Consumer", target: "_blank" },
                        React.createElement("small", null,
                            React.createElement("i", null,
                                _("BTN.FACT"),
                                "."))))),
            React.createElement("section", null,
                React.createElement("h4", null, _("ELECTROLYTE.HEAD3")),
                React.createElement("p", { className: "mt-3" },
                    _("ELECTROLYTE.DESC3"),
                    React.createElement("a", { href: "https://ods.od.nih.gov/factsheets/Potassium-HealthProfessional", target: "_blank" },
                        React.createElement("small", null,
                            React.createElement("i", null,
                                _("BTN.SRC2"),
                                "."))))),
            React.createElement("section", null,
                React.createElement("h4", null, _("ELECTROLYTE.HEAD4")),
                React.createElement("p", { className: "mt-3" },
                    _("ELECTROLYTE.DESC4"),
                    React.createElement("a", { href: "https://ods.od.nih.gov/factsheets/Iron-HealthProfessional", target: "_blank" },
                        React.createElement("small", null,
                            React.createElement("i", null,
                                _("BTN.FACT"),
                                "."))))),
            React.createElement("section", null,
                React.createElement("h4", { style: { color: "#BF4803" } }, _("ELECTROLYTE.HEAD5")),
                React.createElement("p", { className: "mt-3" },
                    _("ELECTROLYTE.DESC5"),
                    React.createElement("a", { href: "https://en.wikipedia.org/wiki/Electrolyte_imbalance", target: "_blank" },
                        React.createElement("small", null,
                            React.createElement("i", null,
                                _("BTN.WIKI"),
                                ".")))))),
        React.createElement("div", { className: "container mb-5 pb-5 text-center" },
            React.createElement("img", { src: "/img/page/electrolyte/electrolyte-app.webp", alt: _("MAIN.P1.IMG"), className: "ms-base-image", width: "512px", height: "512px" })),
        React.createElement(Footer, null));
}
//# sourceMappingURL=electrolyte.js.map