import * as React from "react";
import _, { Locale } from "src/i18n/locale";
import { Footer } from "../organism/footer";
import NavigationBar from "src/atomic/organism/navbar";
import ImageI18N from "src/atomic/atom/img-i18n";
export default function LandingPage() {
    return (React.createElement("div", { className: "flex-grow-1 flex-shrink-0" },
        React.createElement(NavigationBar, null),
        React.createElement("section", { id: "header", className: "ms-s-header" },
            React.createElement("div", { className: "ms-s-offset text-center" },
                React.createElement("div", { className: "row justify-content-center" },
                    React.createElement("div", { className: "col-auto" },
                        React.createElement(ImageI18N, { src: "/img/header_screens.en.512.webp", w: 512, h: 298, cls: "ms-base-image", alt: _("MAIN.HEAD") }),
                        React.createElement("h1", null, _('MAIN.HEAD')),
                        React.createElement("h4", null, _("MAIN.SUBHEAD")),
                        React.createElement("img", { src: "/img/header_watches.webp", width: 241, height: 160, className: "d-block float-end float-sm-start watches-img", alt: _("MAIN.IMG") }))))),
        React.createElement("section", { className: "ms-s-product" },
            React.createElement("div", { className: "ms-s-offset" },
                React.createElement("div", { className: "row" },
                    React.createElement("div", { className: "col p-container" },
                        React.createElement("div", { className: "d-flex p-head" },
                            React.createElement("img", { src: "/img/page/vitamin/logo-vitamin.svg", className: "img-fluid me-3", height: 48, width: 48, alt: _("VITAMIN.ICO") }),
                            React.createElement("div", null,
                                React.createElement("h1", null, _("VITAMIN.HEAD")),
                                React.createElement("p", null, _("VITAMIN.SUBHEAD")))),
                        React.createElement("div", { className: "p-img" },
                            React.createElement(ImageI18N, { src: "/img/page/vitamin/vitamin-home-en.webp", w: 512, h: 512, cls: "mx-auto my-4 img-fluid", alt: _("VITAMIN.IMG") })),
                        React.createElement("div", { className: "p-text" },
                            React.createElement("h4", null, _("VITAMIN.TEXT")),
                            React.createElement("a", { href: Locale.i18nLink("vitamin"), className: "mt-3 ms-btn-large" }, _("VITAMIN.BTN_OPEN"))))))),
        React.createElement("section", { className: "ms-s-product" },
            React.createElement("div", { className: "ms-s-offset" },
                React.createElement("div", { className: "row" },
                    React.createElement("div", { className: "col p-container" },
                        React.createElement("div", { className: "d-flex p-head" },
                            React.createElement("img", { src: "/img/page/body-size/logo-size.svg", className: "img-fluid me-3", height: 48, width: 48, alt: _("SIZE.ICO") }),
                            React.createElement("div", null,
                                React.createElement("h1", null, _("SIZE.HEAD")),
                                React.createElement("p", null, _("SIZE.SUBHEAD")))),
                        React.createElement("div", { className: "p-img" },
                            React.createElement(ImageI18N, { src: "/img/page/body-size/size-home-en.webp", w: 512, h: 512, cls: "mx-auto my-4 img-fluid", alt: _("SIZE.IMG") })),
                        React.createElement("div", { className: "p-text" },
                            React.createElement("h4", null, _("SIZE.TEXT")),
                            React.createElement("a", { href: Locale.i18nLink("bodysize"), className: "mt-3 ms-btn-large" }, _("SIZE.BTN_OPEN"))))))),
        React.createElement("section", { className: "ms-s-product" },
            React.createElement("div", { className: "ms-s-offset" },
                React.createElement("div", { className: "row" },
                    React.createElement("div", { className: "col p-container" },
                        React.createElement("div", { className: "d-flex p-head" },
                            React.createElement("img", { src: "/img/page/electrolyte/logo-electrolyte.svg", className: "img-fluid me-3", height: 48, width: 48, alt: _("ELECTROLYTE.ICO") }),
                            React.createElement("div", null,
                                React.createElement("h1", null, _("ELECTROLYTE.HEAD")),
                                React.createElement("p", null, _("ELECTROLYTE.SUBHEAD")))),
                        React.createElement("div", { className: "p-img" },
                            React.createElement(ImageI18N, { src: "/img/page/electrolyte/electrolyte-home.webp", w: 512, h: 512, cls: "mx-auto my-4 img-fluid", alt: _("ELECTROLYTE.IMG") })),
                        React.createElement("div", { className: "p-text" },
                            React.createElement("h4", null, _("ELECTROLYTE.TEXT")),
                            React.createElement("a", { href: Locale.i18nLink("electrolyte"), className: "mt-3 ms-btn-large" }, _("ELECTROLYTE.BTN_OPEN"))))))),
        React.createElement("section", { className: "ms-s-product" },
            React.createElement("div", { className: "ms-s-offset" },
                React.createElement("div", { className: "row" },
                    React.createElement("div", { className: "col p-container" },
                        React.createElement("div", { className: "d-flex p-head" },
                            React.createElement("img", { src: "/img/page/body-mass/logo-mass.svg", className: "img-fluid me-3", height: 48, width: 48, alt: _("MASS.ICO") }),
                            React.createElement("div", null,
                                React.createElement("h1", null, _("MASS.HEAD")),
                                React.createElement("p", null, _("MASS.SUBHEAD")))),
                        React.createElement("div", { className: "p-img" },
                            React.createElement(ImageI18N, { src: "/img/page/body-mass/mass-home-en.webp", w: 512, h: 512, cls: "mx-auto my-4 px-lg-4 px-0 img-fluid", alt: _("MASS.IMG") })),
                        React.createElement("div", { className: "p-text" },
                            React.createElement("h4", null, _("MASS.TEXT")),
                            React.createElement("a", { href: Locale.i18nLink("bodymass"), className: "mt-3 ms-btn-large" }, _("MASS.BTN_OPEN"))))))),
        React.createElement("section", { className: "ms-s-product" },
            React.createElement("div", { className: "ms-s-offset" },
                React.createElement("div", { className: "row" },
                    React.createElement("div", { className: "col p-container" },
                        React.createElement("div", { className: "d-flex p-head" },
                            React.createElement("img", { src: "/img/page/zinc/logo-zinc.svg", className: "img-fluid me-3", height: 48, width: 48, alt: _("ZINC.ICO") }),
                            React.createElement("div", null,
                                React.createElement("h1", null, _("ZINC.HEAD")),
                                React.createElement("p", null, _("ZINC.SUBHEAD")))),
                        React.createElement("div", { className: "p-img" },
                            React.createElement(ImageI18N, { src: "/img/page/zinc/zinc-app-en.webp", w: 512, h: 512, cls: "mx-auto my-4 img-fluid", alt: _("ZINC.IMG") })),
                        React.createElement("div", { className: "p-text" },
                            React.createElement("h4", null, _("ZINC.TEXT")),
                            React.createElement("a", { href: Locale.i18nLink("bodyzinc"), className: "mt-3 ms-btn-large" }, _("ZINC.BTN_OPEN"))))))),
        React.createElement("section", { className: "ms-s-product my-5" },
            React.createElement("div", { className: "ms-s-offset" },
                React.createElement("div", { className: "row" },
                    React.createElement("div", { className: "col p-container" },
                        React.createElement("div", { className: "d-flex p-head" },
                            React.createElement("img", { src: "/img/page/waistline/logo-waist.svg", className: "img-fluid me-3", height: 48, width: 48, alt: _("WAIST.ICO") }),
                            React.createElement("div", null,
                                React.createElement("h1", null, _("WAIST.HEAD")),
                                React.createElement("p", null, _("WAIST.SUBHEAD")))),
                        React.createElement("div", { className: "p-img" },
                            React.createElement(ImageI18N, { src: "/img/page/waistline/waist-home-en.webp", w: 512, h: 512, cls: "mx-auto my-4 px-lg-4 px-0 img-fluid", alt: _("WAIST.IMG") })),
                        React.createElement("div", { className: "p-text" },
                            React.createElement("h4", null, _("WAIST.TEXT")),
                            React.createElement("a", { href: Locale.i18nLink("waistline"), className: "mt-3 ms-btn-large" }, _("WAIST.BTN_OPEN"))))))),
        React.createElement("section", { className: "ms-s-product" },
            React.createElement("div", { className: "ms-s-offset" },
                React.createElement("div", { className: "row" },
                    React.createElement("div", { className: "col p-container" },
                        React.createElement("div", { className: "d-flex p-head" },
                            React.createElement("img", { src: "/img/page/emotion/logo-emotion.svg", className: "img-fluid me-3", height: 48, width: 48, alt: _("EMOTION.ICO") }),
                            React.createElement("div", null,
                                React.createElement("h1", null, _("EMOTION.HEAD")),
                                React.createElement("p", null, _("EMOTION.SUBHEAD")))),
                        React.createElement("div", { className: "p-img" },
                            React.createElement(ImageI18N, { src: "/img/page/emotion/emotion-home-en.webp", w: 512, h: 512, cls: "mx-auto my-4 img-fluid", alt: _("EMOTION.IMG") })),
                        React.createElement("div", { className: "p-text" },
                            React.createElement("h4", null, _("EMOTION.TEXT")),
                            React.createElement("a", { href: Locale.i18nLink("emotion"), className: "mt-3 ms-btn-large" }, _("EMOTION.BTN_OPEN"))))))),
        React.createElement(Footer, null)));
}
//# sourceMappingURL=main.js.map