import * as React from "react";
import { Footer } from "src/atomic/organism/footer";
import NavigationBar from "src/atomic/organism/navbar";
import _ from "src/i18n/locale";
import PageHeader from "../molecule/page-header";
export default function PrivacyPolicy() {
    return (React.createElement(React.Fragment, null,
        React.createElement(NavigationBar, null),
        React.createElement("div", { className: "ms-base-page pb-5" },
            React.createElement(PageHeader, { title: "PP.HEAD", imgSrc: "/img/privacy.svg", imgAlt: "PP.IMG", imgH: 360, imgW: 428 }),
            React.createElement("section", null,
                React.createElement("h6", null, _("PP.DATE")),
                React.createElement("p", null, _("PP.P1")),
                React.createElement("p", null, _("PP.P2")),
                React.createElement("p", null, _("PP.P3"))),
            React.createElement("section", null,
                React.createElement("hr", null),
                React.createElement("h4", null, _("PP.DEFINITION.HEAD")),
                React.createElement("p", null, _("PP.DEFINITION.P1")),
                React.createElement("p", null, _("PP.DEFINITION.P2")),
                React.createElement("ul", null,
                    React.createElement("li", null,
                        React.createElement("p", null,
                            React.createElement("strong", null, _("PP.DEFINITION.UL.ACCOUNT.STRONG")),
                            _("PP.DEFINITION.UL.ACCOUNT.P1"))),
                    React.createElement("li", null,
                        React.createElement("p", null,
                            React.createElement("strong", null, _("PP.DEFINITION.UL.APP.STRONG")),
                            _("PP.DEFINITION.UL.APP.P1"))),
                    React.createElement("li", null,
                        React.createElement("p", null,
                            React.createElement("strong", null, _("PP.DEFINITION.UL.BUSINESS.STRONG")),
                            _("PP.DEFINITION.UL.BUSINESS.P1"))),
                    React.createElement("li", null,
                        React.createElement("p", null,
                            React.createElement("strong", null, _("PP.DEFINITION.UL.COMPANY.STRONG")),
                            _("PP.DEFINITION.UL.COMPANY.P1"))),
                    React.createElement("li", null,
                        React.createElement("p", null,
                            React.createElement("strong", null, _("PP.DEFINITION.UL.CONSUMER.STRONG")),
                            _("PP.DEFINITION.UL.CONSUMER.P1"))),
                    React.createElement("li", null,
                        React.createElement("p", null,
                            React.createElement("strong", null, _("PP.DEFINITION.UL.COOKIES.STRONG")),
                            _("PP.DEFINITION.UL.COOKIES.P1"))),
                    React.createElement("li", null,
                        React.createElement("p", null,
                            React.createElement("strong", null, _("PP.DEFINITION.UL.COUNTRY.STRONG")),
                            _("PP.DEFINITION.UL.COUNTRY.P1"))),
                    React.createElement("li", null,
                        React.createElement("p", null,
                            React.createElement("strong", null, _("PP.DEFINITION.UL.DEVICE.STRONG")),
                            _("PP.DEFINITION.UL.DEVICE.P1"))),
                    React.createElement("li", null,
                        React.createElement("p", null,
                            React.createElement("strong", null, _("PP.DEFINITION.UL.PERSONAL_DATA.STRONG")),
                            _("PP.DEFINITION.UL.PERSONAL_DATA.P1")),
                        React.createElement("p", null, _("PP.DEFINITION.UL.PERSONAL_DATA.P2"))),
                    React.createElement("li", null,
                        React.createElement("p", null,
                            React.createElement("strong", null, _("PP.DEFINITION.UL.SALE.STRONG")),
                            _("PP.DEFINITION.UL.SALE.P1"))),
                    React.createElement("li", null,
                        React.createElement("p", null,
                            React.createElement("strong", null, _("PP.DEFINITION.UL.SERVICE.STRONG")),
                            _("PP.DEFINITION.UL.SERVICE.P1"))),
                    React.createElement("li", null,
                        React.createElement("p", null,
                            React.createElement("strong", null, _("PP.DEFINITION.UL.SERVICE_PROVIDER.STRONG")),
                            _("PP.DEFINITION.UL.SERVICE_PROVIDER.P1"))),
                    React.createElement("li", null,
                        React.createElement("p", null,
                            React.createElement("strong", null, _("PP.DEFINITION.UL.THIRD_PARTY_MEDIA.STRONG")),
                            _("PP.DEFINITION.UL.THIRD_PARTY_MEDIA.P1"))),
                    React.createElement("li", null,
                        React.createElement("p", null,
                            React.createElement("strong", null, _("PP.DEFINITION.UL.USAGE_DATA.STRONG")),
                            _("PP.DEFINITION.UL.USAGE_DATA.P1"))),
                    React.createElement("li", null,
                        React.createElement("p", null,
                            React.createElement("strong", null, _("PP.DEFINITION.UL.WEBSITE.STRONG")),
                            _("PP.DEFINITION.UL.WEBSITE.P1"),
                            React.createElement("a", { href: "https://martspec.com/", rel: "external nofollow noopener", target: "_blank" }, _("PP.DEFINITION.UL.WEBSITE.A")))),
                    React.createElement("li", null,
                        React.createElement("p", null,
                            React.createElement("strong", null, _("PP.DEFINITION.UL.YOU.STRONG")),
                            _("PP.DEFINITION.UL.YOU.P1"))))),
            React.createElement("section", null,
                React.createElement("hr", null),
                React.createElement("h4", null, _("PP.TYPES_OF_DATA.HEAD4")),
                React.createElement("h5", null, _("PP.TYPES_OF_DATA.HEAD5.PERSONAL_DATA")),
                React.createElement("p", null, _("PP.TYPES_OF_DATA.P1")),
                React.createElement("ul", null,
                    React.createElement("li", null,
                        React.createElement("p", null, _("PP.TYPES_OF_DATA.UL1.EMAIL"))),
                    React.createElement("li", null,
                        React.createElement("p", null, _("PP.TYPES_OF_DATA.UL1.FIRST_LAST_NAMES"))),
                    React.createElement("li", null,
                        React.createElement("p", null, _("PP.TYPES_OF_DATA.UL1.USAGE_DATA")))),
                React.createElement("h5", null, _("PP.TYPES_OF_DATA.HEAD5.USAGE_DATA")),
                React.createElement("p", null, _("PP.TYPES_OF_DATA.P2")),
                React.createElement("p", null, _("PP.TYPES_OF_DATA.P3")),
                React.createElement("p", null, _("PP.TYPES_OF_DATA.P4")),
                React.createElement("p", null, _("PP.TYPES_OF_DATA.P5")),
                React.createElement("h5", null, _("PP.TYPES_OF_DATA.HEAD5.INFORMATION_COLLECTED")),
                React.createElement("p", null,
                    _("PP.TYPES_OF_DATA.P6"),
                    React.createElement("ul", null,
                        React.createElement("li", null,
                            React.createElement("strong", null, _("PP.TYPES_OF_DATA.UL2.MOBILE_ACCESS.STRONG")),
                            _("PP.TYPES_OF_DATA.UL2.MOBILE_ACCESS.TEXT")),
                        React.createElement("li", null,
                            React.createElement("strong", null, _("PP.TYPES_OF_DATA.UL2.MOBILE_DATA.STRONG")),
                            _("PP.TYPES_OF_DATA.UL2.MOBILE_DATA.TEXT")),
                        React.createElement("li", null,
                            React.createElement("strong", null, _("PP.TYPES_OF_DATA.UL2.PUSH_NOTIFICATIONS.STRONG")),
                            _("PP.TYPES_OF_DATA.UL2.PUSH_NOTIFICATIONS.TEXT"))))),
            React.createElement("section", null,
                React.createElement("hr", null),
                React.createElement("h4", null, _("PP.TRACKING.HEAD4")),
                React.createElement("p", null,
                    _("PP.TRACKING.P1.TEXT"),
                    React.createElement("a", { href: "https://termsfeed.com/blog/cookies/", target: "_blank" }, _("PP.TRACKING.P1.A"))),
                React.createElement("p", null, _("PP.TRACKING.P2")),
                React.createElement("ul", null,
                    React.createElement("li", null,
                        React.createElement("p", null,
                            React.createElement("strong", null, _("PP.TRACKING.UL.NECESSARY.P1"))),
                        React.createElement("p", null, _("PP.TRACKING.UL.NECESSARY.P2")),
                        React.createElement("p", null, _("PP.TRACKING.UL.NECESSARY.P3")),
                        React.createElement("p", null, _("PP.TRACKING.UL.NECESSARY.P4"))),
                    React.createElement("li", null,
                        React.createElement("p", null,
                            React.createElement("strong", null, _("PP.TRACKING.UL.FUNCTIONALITY.P1"))),
                        React.createElement("p", null, _("PP.TRACKING.UL.FUNCTIONALITY.P2")),
                        React.createElement("p", null, _("PP.TRACKING.UL.FUNCTIONALITY.P3")),
                        React.createElement("p", null, _("PP.TRACKING.UL.FUNCTIONALITY.P4")))),
                React.createElement("h5", null, _("PP.TRACKING.HEAD5")),
                React.createElement("p", null, _("PP.TRACKING.P3"))),
            React.createElement("section", null,
                React.createElement("hr", null),
                React.createElement("h4", null, _("PP.PERSONAL_DATA.USE.HEAD4")),
                React.createElement("h5", null, _("PP.PERSONAL_DATA.USE.HEAD5.DISCLOSE")),
                React.createElement("ul", null,
                    React.createElement("li", null,
                        React.createElement("strong", null, _("PP.PERSONAL_DATA.USE.UL1.LAW_ENFORCEMENT.STRONG")),
                        _("PP.PERSONAL_DATA.USE.UL1.LAW_ENFORCEMENT.TEXT")),
                    React.createElement("li", null,
                        React.createElement("strong", null, _("PP.PERSONAL_DATA.USE.UL1.BUSINESS_TRANSFER.STRONG")),
                        _("PP.PERSONAL_DATA.USE.UL1.BUSINESS_TRANSFER.TEXT")),
                    React.createElement("li", null,
                        React.createElement("strong", null, _("PP.PERSONAL_DATA.USE.UL1.OTHER.STRONG")),
                        _("PP.PERSONAL_DATA.USE.UL1.OTHER.TEXT"),
                        React.createElement("ul", null,
                            React.createElement("li", null, _("PP.PERSONAL_DATA.USE.UL1.OTHER.UL.L1")),
                            React.createElement("li", null, _("PP.PERSONAL_DATA.USE.UL1.OTHER.UL.L2")),
                            React.createElement("li", null, _("PP.PERSONAL_DATA.USE.UL1.OTHER.UL.L3")),
                            React.createElement("li", null, _("PP.PERSONAL_DATA.USE.UL1.OTHER.UL.L4")),
                            React.createElement("li", null, _("PP.PERSONAL_DATA.USE.UL1.OTHER.UL.L5"))))),
                React.createElement("h5", null, _("PP.PERSONAL_DATA.USE.HEAD5.USE")),
                React.createElement("ul", null,
                    React.createElement("li", null,
                        React.createElement("strong", null, _("PP.PERSONAL_DATA.USE.UL2.L1.STRONG")),
                        _("PP.PERSONAL_DATA.USE.UL2.L1.TEXT")),
                    React.createElement("li", null,
                        React.createElement("strong", null, _("PP.PERSONAL_DATA.USE.UL2.L2.STRONG")),
                        _("PP.PERSONAL_DATA.USE.UL2.L2.TEXT")),
                    React.createElement("li", null,
                        React.createElement("strong", null, _("PP.PERSONAL_DATA.USE.UL2.L3.STRONG")),
                        _("PP.PERSONAL_DATA.USE.UL2.L3.TEXT")),
                    React.createElement("li", null,
                        React.createElement("strong", null, _("PP.PERSONAL_DATA.USE.UL2.L4.STRONG")),
                        _("PP.PERSONAL_DATA.USE.UL2.L4.TEXT")),
                    React.createElement("li", null,
                        React.createElement("strong", null, _("PP.PERSONAL_DATA.USE.UL2.L5.STRONG")),
                        _("PP.PERSONAL_DATA.USE.UL2.L5.TEXT")),
                    React.createElement("li", null,
                        React.createElement("strong", null, _("PP.PERSONAL_DATA.USE.UL2.L6.STRONG")),
                        _("PP.PERSONAL_DATA.USE.UL2.L6.TEXT")),
                    React.createElement("li", null,
                        React.createElement("strong", null, _("PP.PERSONAL_DATA.USE.UL2.L7.STRONG")),
                        _("PP.PERSONAL_DATA.USE.UL2.L7.TEXT")),
                    React.createElement("li", null,
                        React.createElement("strong", null, _("PP.PERSONAL_DATA.USE.UL2.L8.STRONG")),
                        _("PP.PERSONAL_DATA.USE.UL2.L8.TEXT"))),
                React.createElement("h5", null, _("PP.PERSONAL_DATA.USE.HEAD5.SHARING")),
                React.createElement("ul", null,
                    React.createElement("li", null,
                        React.createElement("strong", null, _("PP.PERSONAL_DATA.USE.UL3.L1.STRONG")),
                        _("PP.PERSONAL_DATA.USE.UL3.L1.TEXT")),
                    React.createElement("li", null,
                        React.createElement("strong", null, _("PP.PERSONAL_DATA.USE.UL3.L2.STRONG")),
                        _("PP.PERSONAL_DATA.USE.UL3.L2.TEXT")),
                    React.createElement("li", null,
                        React.createElement("strong", null, _("PP.PERSONAL_DATA.USE.UL3.L3.STRONG")),
                        _("PP.PERSONAL_DATA.USE.UL3.L3.TEXT")),
                    React.createElement("li", null,
                        React.createElement("strong", null, _("PP.PERSONAL_DATA.USE.UL3.L4.STRONG")),
                        _("PP.PERSONAL_DATA.USE.UL3.L4.TEXT")),
                    React.createElement("li", null,
                        React.createElement("strong", null, _("PP.PERSONAL_DATA.USE.UL3.L5.STRONG")),
                        _("PP.PERSONAL_DATA.USE.UL3.L5.TEXT"))),
                React.createElement("h4", null, _("PP.PERSONAL_DATA.RETENTION.HEAD4")),
                React.createElement("p", null, _("PP.PERSONAL_DATA.RETENTION.P1")),
                React.createElement("p", null, _("PP.PERSONAL_DATA.RETENTION.P2")),
                React.createElement("p", null, _("PP.PERSONAL_DATA.RETENTION.P3")),
                React.createElement("h4", null, _("PP.PERSONAL_DATA.TRANSFER.HEAD4")),
                React.createElement("p", null, _("PP.PERSONAL_DATA.TRANSFER.P1")),
                React.createElement("p", null, _("PP.PERSONAL_DATA.TRANSFER.P2")),
                React.createElement("p", null, _("PP.PERSONAL_DATA.TRANSFER.P3")),
                React.createElement("h4", null, _("PP.PERSONAL_DATA.SECURITY.HEAD4")),
                React.createElement("p", null, _("PP.PERSONAL_DATA.SECURITY.P"))),
            React.createElement("section", null,
                React.createElement("hr", null),
                React.createElement("h4", null, _("PP.CHILD.HEAD4")),
                React.createElement("p", null, _("PP.CHILD.P"))),
            React.createElement("section", null,
                React.createElement("hr", null),
                React.createElement("h4", null, _("PP.RIGHTS.HEAD4")),
                React.createElement("p", null, _("PP.RIGHTS.P1")),
                React.createElement("p", null, _("PP.RIGHTS.P2")),
                React.createElement("p", null,
                    _("PP.RIGHTS.P3.TEXT"),
                    React.createElement("a", { "data-custom-class": "link", href: "https://ec.europa.eu/justice/data-protection/bodies/authorities/index_en.htm", rel: "noopener noreferrer", target: "_blank" }, _("PP.RIGHTS.P3.A")),
                    "."),
                React.createElement("p", null,
                    _("PP.RIGHTS.P4.TEXT"),
                    React.createElement("a", { "data-custom-class": "link", href: "https://www.edoeb.admin.ch/edoeb/en/home.html", rel: "noopener noreferrer", target: "_blank" }, _("PP.RIGHTS.P4.A"))),
                React.createElement("h5", null, _("PP.RIGHTS.HEAD5")),
                React.createElement("p", null, _("PP.RIGHTS.P5"))),
            React.createElement("section", null,
                React.createElement("hr", null),
                React.createElement("h4", null, _("PP.CCPA.HEAD4.CCPA")),
                React.createElement("h4", null, _("PP.CCPA.HEAD4.CALIFORNIA")),
                React.createElement("p", null, _("PP.CCPA.P1")),
                React.createElement("p", null, _("PP.CCPA.P2")),
                React.createElement("p", null, _("PP.CCPA.P3")),
                React.createElement("h4", null, _("PP.CCPA.HEAD4.MINOR")),
                React.createElement("p", null, _("PP.CCPA.P4")),
                React.createElement("p", null, _("PP.CCPA.P5")),
                React.createElement("p", null, _("PP.CCPA.P6")),
                React.createElement("h4", null, _("PP.CCPA.HEAD4.EXERCISING")),
                React.createElement("p", null,
                    _("PP.CCPA.P7.TEXT1"),
                    React.createElement("ul", null,
                        React.createElement("li", null, _("PP.CCPA.P7.UL.L1")),
                        React.createElement("li", null, _("PP.CCPA.P7.UL.L2"))),
                    _("PP.CCPA.P7.TEXT2")),
                React.createElement("p", null, _("PP.CCPA.P8")),
                React.createElement("h4", null, _("PP.CCPA.HEAD4.YOUR_RIGHTS")),
                React.createElement("p", null, _("PP.CCPA.P9")),
                React.createElement("ul", null,
                    React.createElement("li", null,
                        React.createElement("strong", null, _("PP.CCPA.UL1.L1.STRONG")),
                        _("PP.CCPA.UL1.L1.TEXT")),
                    React.createElement("li", null,
                        React.createElement("strong", null, _("PP.CCPA.UL1.L2.STRONG")),
                        _("PP.CCPA.UL1.L2.TEXT")),
                    React.createElement("li", null,
                        React.createElement("strong", null, _("PP.CCPA.UL1.L3.STRONG")),
                        _("PP.CCPA.UL1.L3.TEXT")),
                    React.createElement("li", null,
                        React.createElement("strong", null, _("PP.CCPA.UL1.L4.STRONG")),
                        _("PP.CCPA.UL1.L4.TEXT"),
                        React.createElement("ul", null,
                            React.createElement("li", null, _("PP.CCPA.UL1.L4.UL.L1")),
                            React.createElement("li", null, _("PP.CCPA.UL1.L4.UL.L2")),
                            React.createElement("li", null, _("PP.CCPA.UL1.L4.UL.L3")),
                            React.createElement("li", null, _("PP.CCPA.UL1.L4.UL.L4")),
                            React.createElement("li", null, _("PP.CCPA.UL1.L4.UL.L5")))),
                    React.createElement("li", null,
                        React.createElement("strong", null, _("PP.CCPA.UL1.L5.STRONG")),
                        _("PP.CCPA.UL1.L5.TEXT")),
                    React.createElement("li", null,
                        React.createElement("strong", null, _("PP.CCPA.UL1.L6.STRONG")),
                        _("PP.CCPA.UL1.L6.TEXT"),
                        React.createElement("ul", null,
                            React.createElement("li", null, _("PP.CCPA.UL1.L6.UL.L1")),
                            React.createElement("li", null, _("PP.CCPA.UL1.L6.UL.L2")),
                            React.createElement("li", null, _("PP.CCPA.UL1.L6.UL.L3")),
                            React.createElement("li", null, _("PP.CCPA.UL1.L6.UL.L4"))))),
                React.createElement("h4", null, _("PP.CCPA.HEAD4.PERSONAL_INFORMATION")),
                React.createElement("p", null, _("PP.CCPA.P10")),
                React.createElement("p", null, _("PP.CCPA.P11")),
                React.createElement("h5", null, _("PP.CCPA.HEAD5.SHARED")),
                React.createElement("p", null, _("PP.CCPA.P12")),
                React.createElement("p", null, _("PP.CCPA.P13")),
                React.createElement("p", null, _("PP.CCPA.P14")),
                React.createElement("h5", null, _("PP.CCPA.HEAD5.YOUR_RIGHTS")),
                React.createElement("ul", null,
                    React.createElement("li", null, _("PP.CCPA.UL2.L1")),
                    React.createElement("li", null, _("PP.CCPA.UL2.L2")),
                    React.createElement("li", null, _("PP.CCPA.UL2.L3")),
                    React.createElement("li", null, _("PP.CCPA.UL2.L4"))),
                React.createElement("h5", null, _("PP.CCPA.HEAD5.OTHER")),
                React.createElement("ul", null,
                    React.createElement("li", null, _("PP.CCPA.UL3.L1")),
                    React.createElement("li", null, _("PP.CCPA.UL3.L2")),
                    React.createElement("li", null, _("PP.CCPA.UL3.L3")),
                    React.createElement("li", null, _("PP.CCPA.UL3.L4"))),
                React.createElement("p", null, _("PP.CCPA.P15"))),
            React.createElement("section", null,
                React.createElement("hr", null),
                React.createElement("h4", null, _("PP.LINK.HEAD4")),
                React.createElement("p", null, _("PP.LINK.P1")),
                React.createElement("p", null, _("PP.LINK.P2"))),
            React.createElement("section", null,
                React.createElement("hr", null),
                React.createElement("h4", null, _("PP.CHANGES.HEAD4")),
                React.createElement("p", null, _("PP.CHANGES.P1")),
                React.createElement("p", null, _("PP.CHANGES.P2"))),
            React.createElement("section", null,
                React.createElement("hr", null),
                React.createElement("h4", null, _("PP.CONTACT.HEAD4")),
                React.createElement("p", null, _("PP.CONTACT.TEXT")),
                React.createElement("ul", null,
                    React.createElement("li", null,
                        _("PP.CONTACT.UL.L1.TEXT"),
                        React.createElement("a", { href: "https://martspec.com/privacy-policy", rel: "external nofollow noopener", target: "_blank" }, _("PP.CONTACT.UL.L1.A"))),
                    React.createElement("li", null,
                        _("PP.CONTACT.UL.L2.TEXT"),
                        React.createElement("a", { href: _("PP.CONTACT.UL.L2.LINK"), target: "_blank" }, _("PP.CONTACT.UL.L2.A"))),
                    React.createElement("li", null,
                        _("PP.CONTACT.UL.L3.TEXT"),
                        React.createElement("a", { href: _("PP.CONTACT.UL.L3.LINK"), target: "_blank" }, _("PP.CONTACT.UL.L3.A"))),
                    React.createElement("li", null,
                        _("PP.CONTACT.UL.L4.TEXT"),
                        React.createElement("a", { href: _("PP.CONTACT.UL.L4.LINK"), target: "_blank" }, _("PP.CONTACT.UL.L4.A"))))),
            React.createElement("br", { className: "my-5" })),
        React.createElement(Footer, null)));
}
//# sourceMappingURL=private-policy.js.map