import * as React from "react";
import _, { Locale } from "src/i18n/locale";
import { Footer } from "src/atomic/organism/footer";
import NavigationBar from "src/atomic/organism/navbar";
import VitaminItem from "src/atomic/molecule/vitamin-item";
import PageHeader from "../molecule/page-header";
import ImageI18N from "../atom/img-i18n";
const vitamins = {
    VITAMIN_FAT: ["VITAMIN_A", "VITAMIN_D", "VITAMIN_E", "VITAMIN_K"],
    VITAMIN_WATER: ["VITAMIN_B1", "VITAMIN_B2", "VITAMIN_B3", "VITAMIN_B5", "VITAMIN_B6", "VITAMIN_B7", "VITAMIN_B9", "VITAMIN_B12", "VITAMIN_C"],
    MINERAL: ["CALCIUM", "CHLORIDE", "CHROME", "COPPER", "IODINE", "IRON", "MAGNESIUM", "MANGANESE", "MOLYBDENUM", "PHOSPHORUS", "POTASSIUM", "SELENIUM", "SODIUM", "ZINC"]
};
export default function Vitamin() {
    return React.createElement(React.Fragment, null,
        React.createElement(NavigationBar, null),
        React.createElement("div", { className: "ms-base-page ms-base-new vitamin" },
            React.createElement(PageHeader, { title: "VITAMIN.HEAD", subtitleLevel1: "VITAMIN.ABOUT_1", subtitleLevel2: "VITAMIN.ABOUT_2", appId: 1519596234, appDownloadTitle: "VITAMIN.DWN", imgSrc: "/img/page/vitamin/vitamin.webp", imgAlt: "VITAMIN.IMG", imgH: 512, imgW: 512 }),
            React.createElement("section", null,
                React.createElement("div", { className: "row g-4" },
                    React.createElement("div", { className: "col-lg-4" },
                        React.createElement("div", { className: "block bg-blue" },
                            React.createElement("h3", null, _("VITAMIN.LIST1.LI1_HEAD")),
                            React.createElement("p", null, _("VITAMIN.LIST1.LI1_TEXT")))),
                    React.createElement("div", { className: "col-lg-4" },
                        React.createElement("div", { className: "block bg-green" },
                            React.createElement("h3", null, _("VITAMIN.LIST1.LI2_HEAD")),
                            React.createElement("p", null, _("VITAMIN.LIST1.LI2_TEXT")))),
                    React.createElement("div", { className: "col-lg-4" },
                        React.createElement("div", { className: "block bg-blue" },
                            React.createElement("h3", null, _("VITAMIN.LIST1.LI3_HEAD")),
                            React.createElement("p", null, _("VITAMIN.LIST1.LI3_TEXT")))))),
            React.createElement("section", null,
                React.createElement("div", { className: "row" },
                    React.createElement("div", { className: "col-lg-6" },
                        React.createElement("h2", null, _("VITAMIN.HEAD2")),
                        React.createElement("p", { className: "mb-4" }, _("VITAMIN.DESC2_1")),
                        React.createElement("p", { className: "mb-4" }, _("VITAMIN.DESC2_2")),
                        React.createElement("p", { className: "mb-0" }, _("VITAMIN.DESC2_3"))),
                    React.createElement("div", { className: "col-lg-6" },
                        React.createElement(ImageI18N, { src: "/img/page/vitamin/vitamin-screen-desc-en.webp", w: 390, h: 515, cls: "ms-base-image mt-mob-xs", alt: _("VITAMIN.ALT1") })))),
            React.createElement("section", null,
                React.createElement("div", { className: "row" },
                    React.createElement("div", { className: "col-lg-6" },
                        React.createElement(ImageI18N, { src: "/img/page/vitamin/vitamin-screen-edit-en.webp", w: 487, h: 515, cls: "ms-base-image d-none d-lg-block", alt: _("VITAMIN.ALT4") })),
                    React.createElement("div", { className: "col-lg-6" },
                        React.createElement("h2", null, _("VITAMIN.HEAD3")),
                        React.createElement("p", null, _("VITAMIN.DESC3_1")),
                        React.createElement(ImageI18N, { src: "/img/page/vitamin/vitamin-screen-edit-en.webp", w: 487, h: 515, cls: "ms-base-image d-block d-lg-none mb-mob-xs", alt: _("VITAMIN.ALT4") }),
                        React.createElement("h3", null, _("VITAMIN.DESC3_2")),
                        React.createElement("ul", { className: "checkmark-list" },
                            React.createElement("li", null, _("VITAMIN.LIST3.LI1_TEXT")),
                            React.createElement("li", null, _("VITAMIN.LIST3.LI2_TEXT")),
                            React.createElement("li", null, _("VITAMIN.LIST3.LI3_TEXT")),
                            React.createElement("li", null, _("VITAMIN.LIST3.LI4_TEXT")),
                            React.createElement("li", null, _("VITAMIN.LIST3.LI5_TEXT")),
                            React.createElement("li", null, _("VITAMIN.LIST3.LI6_TEXT")))))),
            React.createElement("section", { className: "bg-gray" },
                React.createElement("div", { className: "row" },
                    React.createElement("div", { className: "col-12 mb-2" },
                        React.createElement("h2", null, _("VITAMIN.HEAD4"))),
                    React.createElement("div", { className: "col-12" },
                        React.createElement("ul", { className: "list-with-icons" },
                            React.createElement("li", null,
                                React.createElement("div", { className: "icon" },
                                    React.createElement("img", { src: "/img/atom/icons/icon-defense.svg", alt: _("VITAMIN.ALT5_1") })),
                                React.createElement("div", null,
                                    React.createElement("h3", null, _("VITAMIN.LIST4.LI1_HEAD")),
                                    React.createElement("p", null, _("VITAMIN.LIST4.LI1_TEXT")))),
                            React.createElement("li", null,
                                React.createElement("div", { className: "icon" },
                                    React.createElement("img", { src: "/img/atom/icons/icon-sync.svg", alt: _("VITAMIN.ALT5_2") })),
                                React.createElement("div", null,
                                    React.createElement("h3", null, _("VITAMIN.LIST4.LI2_HEAD")),
                                    React.createElement("p", null, _("VITAMIN.LIST4.LI2_TEXT")))),
                            React.createElement("li", null,
                                React.createElement("div", { className: "icon" },
                                    React.createElement("img", { src: "/img/atom/icons/icon-no-auth.svg", alt: _("VITAMIN.ALT5_3") })),
                                React.createElement("div", null,
                                    React.createElement("h3", null, _("VITAMIN.LIST4.LI3_HEAD")),
                                    React.createElement("p", null, _("VITAMIN.LIST4.LI3_TEXT")))),
                            React.createElement("li", null,
                                React.createElement("div", { className: "icon" },
                                    React.createElement("img", { src: "/img/atom/icons/icon-no-ads.svg", alt: _("VITAMIN.ALT5_4") })),
                                React.createElement("div", null,
                                    React.createElement("h3", null, _("VITAMIN.LIST4.LI4_HEAD")),
                                    React.createElement("p", null, _("VITAMIN.LIST4.LI4_TEXT")))),
                            React.createElement("li", null,
                                React.createElement("div", { className: "icon" },
                                    React.createElement("img", { src: "/img/atom/icons/icon-bell.svg", alt: _("VITAMIN.ALT5_4") })),
                                React.createElement("div", null,
                                    React.createElement("h3", null, _("VITAMIN.LIST4.LI5_HEAD")),
                                    React.createElement("p", null, _("VITAMIN.LIST4.LI5_TEXT")))),
                            React.createElement("li", null,
                                React.createElement("div", { className: "icon no-filter" },
                                    React.createElement("img", { src: "/img/atom/icons/icon-apple-health.svg", alt: _("VITAMIN.ALT5_4") })),
                                React.createElement("div", null,
                                    React.createElement("h3", null, _("VITAMIN.LIST4.LI6_HEAD")),
                                    React.createElement("p", null, _("VITAMIN.LIST4.LI6_TEXT")))))))),
            React.createElement("section", { className: "bg-gray bg-merge-top" },
                React.createElement("div", { className: "row mb-0" },
                    React.createElement("div", { className: "col-12" },
                        React.createElement("div", { className: "block bg-green" },
                            React.createElement("h2", { className: "mb-6" }, _("VITAMIN.HEAD5")),
                            React.createElement("ul", { className: "counters-list" },
                                React.createElement("li", null,
                                    React.createElement("h1", null, _("VITAMIN.LIST5.LI1_HEAD")),
                                    React.createElement("p", null, _("VITAMIN.LIST5.LI1_TEXT"))),
                                React.createElement("li", null,
                                    React.createElement("h1", null, _("VITAMIN.LIST5.LI2_HEAD")),
                                    React.createElement("p", null, _("VITAMIN.LIST5.LI2_TEXT"))),
                                React.createElement("li", null,
                                    React.createElement("h1", null, _("VITAMIN.LIST5.LI3_HEAD")),
                                    React.createElement("p", null, _("VITAMIN.LIST5.LI3_TEXT"))),
                                React.createElement("li", null,
                                    React.createElement("h1", null, _("VITAMIN.LIST5.LI4_HEAD")),
                                    React.createElement("p", null, _("VITAMIN.LIST5.LI4_TEXT")))))))),
            React.createElement("section", { className: "vitamins-list" },
                React.createElement("div", { className: "row" }, Object
                    .entries(vitamins)
                    .map(([vitGroupName, vitList]) => (React.createElement("div", { key: "vitamins-group-" + vitGroupName, className: "col-12 vit-group" },
                    React.createElement("div", { className: "py-3 px-5 vit-group-name" }, _("VITAMIN." + vitGroupName + ".NAME")),
                    vitList.map(vit => React.createElement(VitaminItem, { key: vit, id: vit }))))))),
            React.createElement("section", null,
                React.createElement("div", { className: "row text-lg-start text-center page-bottom" },
                    React.createElement("div", { className: "col-12 block bg-violet" },
                        React.createElement("div", null,
                            React.createElement("h2", null, _("VITAMIN.HEAD6")),
                            React.createElement("p", { className: "flex-grow-1" }, _("VITAMIN.DESC6")),
                            React.createElement("a", { href: `https://apps.apple.com/${_("COUNTRY_CODE")}/app/id1519596234?l=${Locale.language}`, target: "_blank", title: _("VITAMIN.DWN"), className: "ms-btn-apple mt-5 mx-lg-0 mx-auto", style: { backgroundImage: 'url(/img/apple_btn/' + Locale.language + '.svg)' } })),
                        React.createElement(ImageI18N, { src: "/img/page/vitamin/vitamin-screen-app-en.webp", w: 400, h: 400, cls: "ms-base-image ms-lg-auto me-lg-0", alt: _("VITAMIN.ALT4") }))))),
        React.createElement(Footer, null));
}
//# sourceMappingURL=vitamin.js.map