import * as React from "react";
import _, { Locale } from "src/i18n/locale";
import SocialBar from "src/atomic/organism/social-bar";
export function LanguageSwitcher() {
    return (React.createElement("div", { className: "btn-group btn-group-toggle text-center", "data-toggle": "buttons" },
        React.createElement("button", { className: `ms-btn-lang ${Locale.language == "en" ? 'disabled' : 'active'} language`, onClick: () => Locale.language = "en" }, "English"),
        React.createElement("span", null, "|"),
        React.createElement("button", { className: `ms-btn-lang ${Locale.language == "ru" ? 'disabled' : 'active'} language`, onClick: () => Locale.language = "ru" }, "\u0420\u0443\u0441\u0441\u043A\u0438\u0439")));
}
export const Footer = () => React.createElement("footer", null,
    React.createElement("div", { className: "px-0 py-5" },
        React.createElement("div", { className: "ms-s-offset my-2" },
            React.createElement("div", { className: "row" },
                React.createElement("div", { className: "col-md-4 col-7 d-flex flex-column" },
                    React.createElement("h2", { className: "mb-4" },
                        " ",
                        _("NAV.ABOUT").toUpperCase(),
                        " "),
                    React.createElement("a", { className: "footer-link mb-1", href: Locale.i18nLink("about") },
                        " ",
                        _("ABOUT.HEAD"),
                        " "),
                    React.createElement("a", { className: "footer-link mb-1", href: Locale.i18nLink("mission") },
                        " ",
                        _("MISSION.HEAD"),
                        " "),
                    React.createElement("a", { className: "footer-link mb-1", href: Locale.i18nLink("team") },
                        " ",
                        _("TEAM.HEAD"),
                        " "),
                    React.createElement("a", { className: "footer-link", href: Locale.i18nLink("privacy-policy") },
                        " ",
                        _("PP.HEAD"),
                        " ")),
                React.createElement("div", { className: "col-md-4 col-5 d-flex flex-column" },
                    React.createElement("h2", { className: "mb-4" },
                        " ",
                        _("NAV.APPS").toUpperCase(),
                        " "),
                    React.createElement("a", { className: "footer-link mb-1", href: Locale.i18nLink("vitamin") },
                        " ",
                        _("VITAMIN.HEAD"),
                        " "),
                    React.createElement("a", { className: "footer-link mb-1", href: Locale.i18nLink("bodysize") },
                        " ",
                        _("SIZE.HEAD"),
                        " "),
                    React.createElement("a", { className: "footer-link mb-1", href: Locale.i18nLink("electrolyte") },
                        " ",
                        _("ELECTROLYTE.HEAD"),
                        " "),
                    React.createElement("a", { className: "footer-link mb-1", href: Locale.i18nLink("bodymass") },
                        " ",
                        _("MASS.HEAD"),
                        " "),
                    React.createElement("a", { className: "footer-link mb-1", href: Locale.i18nLink("bodyzinc") },
                        " ",
                        _("ZINC.HEAD"),
                        " "),
                    React.createElement("a", { className: "footer-link mb-1", href: Locale.i18nLink("waistline") },
                        " ",
                        _("WAIST.HEAD"),
                        " "),
                    React.createElement("a", { className: "footer-link mb-1", href: Locale.i18nLink("emotion") },
                        " ",
                        _("EMOTION.HEAD"),
                        " ")),
                React.createElement("div", { className: "col-md-4 col-12 d-flex flex-md-column flex-row-reverse px-0 icon-container" },
                    React.createElement("div", null,
                        React.createElement("a", { href: `https://apps.apple.com/${_("COUNTRY_CODE")}/developer/martspec-llc/id1506250419?l=${Locale.language}`, target: "_blank", title: _("FOOTER.APPLE_BTN.TITLE"), className: "ms-btn-apple" },
                            React.createElement("img", { src: '/img/apple_btn/' + Locale.language + '.svg', alt: _("FOOTER.APPLE_BTN.ALT") }))),
                    React.createElement(SocialBar, { color: "white" }))))),
    React.createElement("div", { className: "row" },
        React.createElement("hr", null)),
    React.createElement("div", { className: "ms-s-offset copyright" },
        React.createElement("div", { className: "row" },
            React.createElement("span", { className: "px-2" }, _("FOOTER.C")))),
    React.createElement("br", null));
//# sourceMappingURL=footer.js.map