import * as React from "react";
import _, { Locale } from "src/i18n/locale";
import { Footer } from "src/atomic/organism/footer";
import NavigationBar from "src/atomic/organism/navbar";
import ImageI18N from "src/atomic/atom/img-i18n";
import PageHeader from "../../molecule/page-header";
export default function Biorhythms() {
    const rhythmsList = [
        {
            name: "PHYS",
            bgColor: "yellow",
            liCount: 6,
            isFirst: true
        },
        {
            name: "EMOT",
            bgColor: "green",
            liCount: 5,
            isFirst: false
        },
        {
            name: "INTEL",
            bgColor: "violet",
            liCount: 6,
            isFirst: false
        },
    ];
    const shouldContentCollapse = window.innerWidth <= 992;
    return React.createElement(React.Fragment, null,
        React.createElement(NavigationBar, null),
        React.createElement("div", { className: "ms-base-page ms-base-new emotion biorhythms" },
            React.createElement(PageHeader, { title: "BIORHYTHMS.HEAD", appId: 1562956213, appDownloadTitle: "BIORHYTHMS.DWN", imgSrc: "/img/biorhythms.png", imgAlt: "BIORHYTHMS.IMG", imgH: 512, imgW: 512 }),
            React.createElement("section", null,
                React.createElement("div", { className: "row" },
                    React.createElement("div", { className: "col-12" },
                        React.createElement("h2", null, _("BIORHYTHMS.HEAD1")),
                        React.createElement("div", { className: "columns-with-collapse" },
                            React.createElement("div", null,
                                React.createElement("p", null, _("BIORHYTHMS.DESK1_1")),
                                React.createElement("a", { role: "button", "data-bs-toggle": "collapse", href: "#firstCollapse", "aria-expanded": !shouldContentCollapse, "aria-controls": "firstCollapse", className: "ms-read-more-btn ms-content-collapse-btn d-lg-none" },
                                    React.createElement("span", null, _("BIORHYTHMS.BTN1")))),
                            React.createElement("div", { id: "firstCollapse", className: "column collapse" + (shouldContentCollapse ? "" : " show") },
                                React.createElement("p", null, _("BIORHYTHMS.DESK1_2"))))))),
            React.createElement("section", { className: "bg-gray" },
                React.createElement("div", { id: "rhythms-carousel", className: "carousel slide carousel-fade", "data-bs-ride": "carousel" },
                    React.createElement("div", { className: "row" },
                        React.createElement("div", { className: "col-lg-4 col-12 mb-mob-xxs" },
                            React.createElement("div", { className: "carousel-indicators indicators" },
                                React.createElement("a", { role: "button", href: "#rhythms-carousel", "data-bs-slide-to": "0", className: "active", "aria-current": "true" },
                                    React.createElement("h2", null, _("BIORHYTHMS.RHYTHMS.PHYS.HEAD"))),
                                React.createElement("a", { role: "button", href: "#rhythms-carousel", "data-bs-slide-to": "1" },
                                    React.createElement("h2", null, _("BIORHYTHMS.RHYTHMS.EMOT.HEAD"))),
                                React.createElement("a", { role: "button", href: "#rhythms-carousel", "data-bs-slide-to": "2" },
                                    React.createElement("h2", { className: "mb-0" }, _("BIORHYTHMS.RHYTHMS.INTEL.HEAD"))))),
                        React.createElement("div", { className: "col-lg-8 col-12" },
                            React.createElement("div", { className: "carousel-inner" }, rhythmsList.map(rhythm => (React.createElement("div", { key: "biorhythm-" + rhythm.name, className: "px-lg-3 carousel-item" + (rhythm.isFirst ? " active" : "") },
                                React.createElement("p", null, _("BIORHYTHMS.RHYTHMS." + rhythm.name + ".DESK")),
                                React.createElement("div", { className: "block bg-" + rhythm.bgColor },
                                    React.createElement("h3", { className: "" }, _("BIORHYTHMS.RHYTHMS.LIST_HEAD")),
                                    React.createElement("ul", null, [...Array(rhythm.liCount).keys()].map(idx => {
                                        idx++;
                                        return (React.createElement("li", { key: "biorhythm-" + rhythm.name + "-li" + idx }, _("BIORHYTHMS.RHYTHMS." + rhythm.name + ".LI" + idx)));
                                    }))))))))))),
            React.createElement("section", null,
                React.createElement("div", { className: "row mb-0" },
                    React.createElement("div", { className: "col-6" },
                        React.createElement("h2", null, _("BIORHYTHMS.HEAD2")),
                        React.createElement("p", { className: "" }, _("BIORHYTHMS.DESK2")))),
                React.createElement("div", { className: "row justify-content-center" },
                    React.createElement("div", { className: "col-lg-8 col-12" },
                        React.createElement("img", { src: "/img/biorhythms_diagram_1.webp", className: "ms-base-image mx-auto", height: 283, width: 848, alt: _("BIORHYTHMS.ALT2") }))),
                React.createElement("div", { className: "row g-4 justify-content-center" },
                    React.createElement("div", { className: "col-lg-4 col-12" },
                        React.createElement("div", { className: "block bg-green" },
                            React.createElement("h3", null, _("BIORHYTHMS.LIST2.LI1_HEAD")),
                            React.createElement("p", null, _("BIORHYTHMS.LIST2.LI1_TEXT")))),
                    React.createElement("div", { className: "col-lg-4 col-12" },
                        React.createElement("div", { className: "block bg-yellow" },
                            React.createElement("h3", null, _("BIORHYTHMS.LIST2.LI2_HEAD")),
                            React.createElement("p", null, _("BIORHYTHMS.LIST2.LI2_TEXT")))),
                    React.createElement("div", { className: "col-lg-4 col-12" },
                        React.createElement("div", { className: "block bg-orange" },
                            React.createElement("h3", null, _("BIORHYTHMS.LIST2.LI3_HEAD")),
                            React.createElement("p", null, _("BIORHYTHMS.LIST2.LI3_TEXT")))),
                    React.createElement("div", { className: "col-lg-4 col-12" },
                        React.createElement("div", { className: "block bg-blue" },
                            React.createElement("h3", null, _("BIORHYTHMS.LIST2.LI4_HEAD")),
                            React.createElement("p", null, _("BIORHYTHMS.LIST2.LI4_TEXT")))),
                    React.createElement("div", { className: "col-lg-4 col-12" },
                        React.createElement("div", { className: "block bg-violet" },
                            React.createElement("h3", null, _("BIORHYTHMS.LIST2.LI5_HEAD")),
                            React.createElement("p", null, _("BIORHYTHMS.LIST2.LI5_TEXT")))))),
            React.createElement("section", null,
                React.createElement("div", { className: "row" },
                    React.createElement("div", { className: "col-lg-6 d-table" },
                        React.createElement("div", { className: "d-table-cell align-middle" },
                            React.createElement("h2", null, _("BIORHYTHMS.HEAD3")),
                            React.createElement("p", null, _("BIORHYTHMS.DESK3_1")),
                            React.createElement("div", { className: "mb-6" },
                                React.createElement("h3", null, _("BIORHYTHMS.DESK3_2")),
                                React.createElement("ul", { className: "checkmark-list" },
                                    React.createElement("li", null, _("BIORHYTHMS.LIST3.LI1_TEXT")),
                                    React.createElement("li", null, _("BIORHYTHMS.LIST3.LI2_TEXT")),
                                    React.createElement("li", null, _("BIORHYTHMS.LIST3.LI3_TEXT")),
                                    React.createElement("li", null, _("BIORHYTHMS.LIST3.LI4_TEXT")))),
                            React.createElement(ImageI18N, { src: "/img/biorhythms_screen_1.en.512.webp", w: 207, h: 402, cls: "ms-base-image d-block d-lg-none mb-mob-xxs", alt: _("BIORHYTHMS.ALT3") }),
                            React.createElement("p", { className: "mb-0" }, _("BIORHYTHMS.DESK3_3")))),
                    React.createElement("div", { className: "col-lg-6 d-flex align-items-center" },
                        React.createElement(ImageI18N, { src: "/img/biorhythms_screen_1.en.512.webp", w: 292, h: 563, cls: "ms-base-image d-none d-lg-block", alt: _("BIORHYTHMS.ALT3") })))),
            React.createElement("section", null,
                React.createElement("div", { className: "row" },
                    React.createElement("div", { className: "col-lg-6" },
                        React.createElement("h2", null, _("BIORHYTHMS.HEAD4")),
                        React.createElement("p", { className: "mb-0" }, _("BIORHYTHMS.DESK4")))),
                React.createElement("div", { className: "row" },
                    React.createElement("div", { className: "col-12" },
                        React.createElement("ul", { className: "list-with-icons" },
                            React.createElement("li", null,
                                React.createElement("div", { className: "icon" },
                                    React.createElement("img", { src: "/img/atom/icons/icon-decrease.svg", alt: _("BIORHYTHMS.ALT4_1") })),
                                React.createElement("div", null,
                                    React.createElement("h3", null, _("BIORHYTHMS.LIST4.LI1_HEAD")),
                                    React.createElement("p", null, _("BIORHYTHMS.LIST4.LI1_TEXT")))),
                            React.createElement("li", null,
                                React.createElement("div", { className: "icon" },
                                    React.createElement("img", { src: "/img/atom/icons/icon-sleep.svg", alt: _("BIORHYTHMS.ALT4_2") })),
                                React.createElement("div", null,
                                    React.createElement("h3", null, _("BIORHYTHMS.LIST4.LI2_HEAD")),
                                    React.createElement("p", null, _("BIORHYTHMS.LIST4.LI2_TEXT")))),
                            React.createElement("li", null,
                                React.createElement("div", { className: "icon" },
                                    React.createElement("img", { src: "/img/atom/icons/icon-depression.svg", alt: _("BIORHYTHMS.ALT4_3") })),
                                React.createElement("div", null,
                                    React.createElement("h3", null, _("BIORHYTHMS.LIST4.LI3_HEAD")),
                                    React.createElement("p", null, _("BIORHYTHMS.LIST4.LI3_TEXT")))),
                            React.createElement("li", null,
                                React.createElement("div", { className: "icon" },
                                    React.createElement("img", { src: "/img/atom/icons/icon-no-appetite.svg", alt: _("BIORHYTHMS.ALT4_4") })),
                                React.createElement("div", null,
                                    React.createElement("h3", null, _("BIORHYTHMS.LIST4.LI4_HEAD")),
                                    React.createElement("p", null, _("BIORHYTHMS.LIST4.LI4_TEXT")))))))),
            React.createElement("section", null,
                React.createElement("div", { className: "row text-lg-start text-center page-bottom" },
                    React.createElement("div", { className: "col-12 block bg-violet" },
                        React.createElement("div", null,
                            React.createElement("h2", null, _("BIORHYTHMS.HEAD5")),
                            React.createElement("p", { className: "flex-grow-1" }, _("BIORHYTHMS.DESK5")),
                            React.createElement("a", { href: `https://apps.apple.com/${_("COUNTRY_CODE")}/app/id1562956213?l=${Locale.language}`, target: "_blank", title: _("BIORHYTHMS.DWN"), className: "ms-btn-apple mt-5 mx-lg-0 mx-auto", style: { backgroundImage: 'url(/img/apple_btn/' + Locale.language + '.svg)' } })),
                        React.createElement(ImageI18N, { src: "/img/page/emotion/emotion-screen-app-en.webp", w: 400, h: 400, cls: "ms-base-image ms-lg-auto me-lg-0", alt: _("BIORHYTHMS.ALT5") }))))),
        React.createElement(Footer, null));
}
//# sourceMappingURL=biorhythms.js.map